# Generated by Django 5.0.2 on 2024-03-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_rename_user_profile_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
