# Generated by Django 5.0.2 on 2024-02-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration_start', models.DateField()),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'festivals',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('festivals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Venues.festivals')),
            ],
            options={
                'db_table': 'places',
            },
        ),
    ]
