# Generated by Django 5.0.2 on 2024-02-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0004_remove_festivals_duration_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='best_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
