# Generated by Django 5.0.2 on 2024-03-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0005_places_best_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='cities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='states',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
