# Generated by Django 5.0.2 on 2024-03-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0014_savedplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
