# Generated by Django 5.0.2 on 2024-03-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0015_places_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedplaces',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
