# Generated by Django 5.0.2 on 2024-03-23 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_rename_userprofile_profile_alter_profile_table'),
        ('Venues', '0016_savedplaces_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedplaces',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.profile'),
        ),
        migrations.AlterField(
            model_name='uservisits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.profile'),
        ),
    ]
