# Generated by Django 5.0.2 on 2024-03-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0017_alter_savedplaces_user_alter_uservisits_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festivals',
            old_name='festivals',
            new_name='place',
        ),
    ]
