# Generated by Django 5.0.2 on 2024-03-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0018_rename_festivals_festivals_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('best_time', models.CharField(blank=True, max_length=200, null=True)),
                ('cast_image', models.ImageField(blank=True, null=True, upload_to='CastPics/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='EventPics/')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
