# Generated by Django 5.0.2 on 2024-03-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0019_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='best_time',
            new_name='timing',
        ),
    ]
