# Generated by Django 5.0.2 on 2024-03-26 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0020_rename_best_time_events_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='cast_image',
        ),
        migrations.CreateModel(
            name='CastImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_image', models.ImageField(blank=True, null=True, upload_to='CastImage/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_images', to='Venues.events')),
            ],
            options={
                'db_table': 'cast_images',
            },
        ),
    ]
