# Generated by Django 5.0.2 on 2024-03-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0021_remove_events_cast_image_castimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_image', to='Venues.events'),
        ),
    ]
