# Generated by Django 5.0.2 on 2024-03-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_rename_userprofile_profile_alter_profile_table'),
        ('Venues', '0022_alter_castimage_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Venues.places')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.profile')),
            ],
            options={
                'db_table': 'done_events',
            },
        ),
    ]
